from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    ENVIRONMENT: str = "development"
    API_PORT: int = 8000

    DB_HOST: str
    DB_PORT: int = 5432
    DB_USER: str
    DB_PASSWORD: str
    DB_NAME: str

    RABBITMQ_HOST: str
    RABBITMQ_PORT: int = 5672
    RABBITMQ_USER: str
    RABBITMQ_PASSWORD: str

    REDIS_HOST: str
    REDIS_PORT: int = 6379
    REDIS_PASSWORD: str = ""

    SECRET_KEY: str
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 1440

    SMTP_HOST: str
    SMTP_PORT: int = 587
    SMTP_USER: str
    SMTP_PASSWORD: str
    EMAIL_FROM: str

    ATS_GREENHOUSE_BOARDS: str = ""
    ATS_LEVER_COMPANIES: str = ""
    ATS_ASHBY_ORGANIZATIONS: str = ""
    ATS_MAX_JOBS_PER_SOURCE: int = 30
    ATS_ENABLE_MOCK_FALLBACK: bool = True

    PIPELINE_RUN_LOCK_TTL_SECONDS: int = 900
    PIPELINE_LAST_RUN_TTL_SECONDS: int = 86400
    PIPELINE_EVENT_DEDUPE_TTL_SECONDS: int = 21600
    PIPELINE_RETRY_MAX_ATTEMPTS: int = 3
    PIPELINE_RETRY_BASE_DELAY_SECONDS: int = 2

    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8")


settings = Settings()

# Application constants (kept next to settings for one import surface)
COOKIE_AUTH = "auth"
COOKIE_AUTH_RESET = "auth_reset"

AUTH_COOKIE_MAX_AGE = 259200
RESET_COOKIE_MAX_AGE = 900
RESET_CODE_REDIS_TTL = 600

EMAIL_QUEUE = "email-queue"

INGESTION_JOBS_QUEUE = "ingestion.jobs"
JOBS_NORMALIZED_QUEUE = "jobs.normalized"
SCORING_JOBS_QUEUE = "scoring.jobs"
SHORTLIST_APPLY_QUEUE = "shortlist.apply"
RETRY_APPLY_QUEUE = "retry.apply"
DIGEST_EMAIL_QUEUE = "digest.email"

HTTP_CLIENT_TIMEOUT_SECONDS = 20.0
HTTP_CLIENT_MAX_CONNECTIONS = 100
HTTP_CLIENT_MAX_KEEPALIVE_CONNECTIONS = 20

ATS_GREENHOUSE_BOARDS = settings.ATS_GREENHOUSE_BOARDS
ATS_LEVER_COMPANIES = settings.ATS_LEVER_COMPANIES
ATS_ASHBY_ORGANIZATIONS = settings.ATS_ASHBY_ORGANIZATIONS
ATS_MAX_JOBS_PER_SOURCE = settings.ATS_MAX_JOBS_PER_SOURCE
ATS_ENABLE_MOCK_FALLBACK = settings.ATS_ENABLE_MOCK_FALLBACK

PIPELINE_RUN_LOCK_KEY_PREFIX = "pipeline:run:lock"
PIPELINE_LAST_RUN_KEY_PREFIX = "pipeline:run:last"
PIPELINE_SCORING_PROGRESS_KEY_PREFIX = "pipeline:run:scoring:processed"
PIPELINE_SCORING_FAILED_KEY_PREFIX = "pipeline:run:scoring:failed"
PIPELINE_SCORING_DIGEST_TRIGGER_KEY_PREFIX = "pipeline:run:scoring:digest_triggered"
PIPELINE_RUN_LOCK_TTL_SECONDS = settings.PIPELINE_RUN_LOCK_TTL_SECONDS
PIPELINE_LAST_RUN_TTL_SECONDS = settings.PIPELINE_LAST_RUN_TTL_SECONDS
PIPELINE_EVENT_DEDUPE_KEY_PREFIX = "pipeline:event:dedupe"
PIPELINE_EVENT_DEDUPE_TTL_SECONDS = settings.PIPELINE_EVENT_DEDUPE_TTL_SECONDS
PIPELINE_RETRY_MAX_ATTEMPTS = settings.PIPELINE_RETRY_MAX_ATTEMPTS
PIPELINE_RETRY_BASE_DELAY_SECONDS = settings.PIPELINE_RETRY_BASE_DELAY_SECONDS

ROLE_RANK_BY_NAME = {"BASIC": 1, "ADMIN": 2}

# Rate limiting (per path + IP; see core.security.rate_limit)
RATE_LIMIT_LOGIN_MAX_REQUESTS = 5
RATE_LIMIT_LOGIN_WINDOW_SECONDS = 300
RATE_LIMIT_FORGET_PASSWORD_MAX_REQUESTS = 3
RATE_LIMIT_FORGET_PASSWORD_WINDOW_SECONDS = 3600
RATE_LIMIT_VALIDATE_CODE_MAX_REQUESTS = 10
RATE_LIMIT_VALIDATE_CODE_WINDOW_SECONDS = 300
