from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    ENVIRONMENT: str = "development"
    API_PORT: int = 8000

    DB_HOST: str
    DB_PORT: int = 5432
    DB_USER: str
    DB_PASSWORD: str
    DB_NAME: str

    RABBITMQ_HOST: str
    RABBITMQ_PORT: int = 5672
    RABBITMQ_USER: str
    RABBITMQ_PASSWORD: str

    REDIS_HOST: str
    REDIS_PORT: int = 6379
    REDIS_PASSWORD: str = ""

    SECRET_KEY: str
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 1440

    SMTP_HOST: str
    SMTP_PORT: int = 587
    SMTP_USER: str
    SMTP_PASSWORD: str
    EMAIL_FROM: str

    ATS_GREENHOUSE_BOARDS: str = ""
    ATS_LEVER_COMPANIES: str = ""
    ATS_ASHBY_ORGANIZATIONS: str = ""
    ATS_MAX_JOBS_PER_SOURCE: int = 30
    ATS_ENABLE_MOCK_FALLBACK: bool = True
    INGESTION_RELEVANCE_ENABLED: bool = True
    INGESTION_RELEVANCE_THRESHOLD: float = 0.45
    INGESTION_RELEVANCE_EXPLORATION_RATE: float = 0.10
    INGESTION_RELEVANCE_MIN_JOBS: int = 40

    OPENAI_API_KEY: str = ""
    AI_TYR_MODEL: str = "gpt-5.4-mini"
    AI_REQUEST_TIMEOUT_SECONDS: int = 30
    AI_SCORING_ENABLED: bool = True
    AI_SCORING_WEIGHT: float = 0.20
    AI_DETERMINISTIC_WEIGHT: float = 0.80
    AI_MIN_CONFIDENCE: float = 0.45
    AI_MIN_CONTEXT_QUALITY: float = 0.35
    AI_MAX_EFFECTIVE_WEIGHT: float = 0.40
    AI_SCORING_MIN_DETERMINISTIC_SCORE: float = 55.0
    AI_SCORING_MIN_ROLE_MATCH: float = 0.25
    AI_SCORING_MIN_SKILL_OVERLAP: float = 0.20
    AI_MAX_CALLS_PER_RUN: int = 120
    AI_SCORING_CACHE_ENABLED: bool = True
    AI_SCORE_DESCRIPTION_MAX_CHARS: int = 1200
    AI_SCORE_REQUIREMENTS_MAX_CHARS: int = 1200
    AI_SCORE_SUMMARY_MAX_CHARS: int = 700

    RESUME_MAX_FILE_SIZE_BYTES: int = 5242880
    RESUME_ALLOWED_MIME_TYPES: str = "application/pdf"
    RESUME_MIN_EXTRACTED_TEXT_CHARS: int = 80
    RESUME_AI_MAX_INPUT_CHARS: int = 12000

    PIPELINE_RUN_LOCK_TTL_SECONDS: int = 900
    PIPELINE_LAST_RUN_TTL_SECONDS: int = 86400
    PIPELINE_EVENT_DEDUPE_TTL_SECONDS: int = 21600
    PIPELINE_RETRY_MAX_ATTEMPTS: int = 3
    PIPELINE_RETRY_BASE_DELAY_SECONDS: int = 2

    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8")


settings = Settings()

# Application constants (kept next to settings for one import surface)
COOKIE_AUTH = "auth"
COOKIE_AUTH_RESET = "auth_reset"

AUTH_COOKIE_MAX_AGE = 259200
RESET_COOKIE_MAX_AGE = 900
RESET_CODE_REDIS_TTL = 600

EMAIL_QUEUE = "email-queue"

INGESTION_JOBS_QUEUE = "ingestion.jobs"
JOBS_NORMALIZED_QUEUE = "jobs.normalized"
SCORING_JOBS_QUEUE = "scoring.jobs"
SHORTLIST_APPLY_QUEUE = "shortlist.apply"
RETRY_APPLY_QUEUE = "retry.apply"
DIGEST_EMAIL_QUEUE = "digest.email"

HTTP_CLIENT_TIMEOUT_SECONDS = 20.0
HTTP_CLIENT_MAX_CONNECTIONS = 100
HTTP_CLIENT_MAX_KEEPALIVE_CONNECTIONS = 20

ATS_GREENHOUSE_BOARDS = settings.ATS_GREENHOUSE_BOARDS
ATS_LEVER_COMPANIES = settings.ATS_LEVER_COMPANIES
ATS_ASHBY_ORGANIZATIONS = settings.ATS_ASHBY_ORGANIZATIONS
ATS_MAX_JOBS_PER_SOURCE = settings.ATS_MAX_JOBS_PER_SOURCE
ATS_ENABLE_MOCK_FALLBACK = settings.ATS_ENABLE_MOCK_FALLBACK
INGESTION_RELEVANCE_ENABLED = settings.INGESTION_RELEVANCE_ENABLED
INGESTION_RELEVANCE_THRESHOLD = settings.INGESTION_RELEVANCE_THRESHOLD
INGESTION_RELEVANCE_EXPLORATION_RATE = settings.INGESTION_RELEVANCE_EXPLORATION_RATE
INGESTION_RELEVANCE_MIN_JOBS = settings.INGESTION_RELEVANCE_MIN_JOBS

PIPELINE_RUN_LOCK_KEY_PREFIX = "pipeline:run:lock"
PIPELINE_LAST_RUN_KEY_PREFIX = "pipeline:run:last"
PIPELINE_SCORING_PROGRESS_KEY_PREFIX = "pipeline:run:scoring:processed"
PIPELINE_SCORING_FAILED_KEY_PREFIX = "pipeline:run:scoring:failed"
PIPELINE_SCORING_DIGEST_TRIGGER_KEY_PREFIX = "pipeline:run:scoring:digest_triggered"
PIPELINE_RUN_AI_CALLS_KEY_PREFIX = "pipeline:run:ai:calls"
PIPELINE_RUN_LOCK_TTL_SECONDS = settings.PIPELINE_RUN_LOCK_TTL_SECONDS
PIPELINE_LAST_RUN_TTL_SECONDS = settings.PIPELINE_LAST_RUN_TTL_SECONDS
PIPELINE_EVENT_DEDUPE_KEY_PREFIX = "pipeline:event:dedupe"
PIPELINE_EVENT_DEDUPE_TTL_SECONDS = settings.PIPELINE_EVENT_DEDUPE_TTL_SECONDS
PIPELINE_RETRY_MAX_ATTEMPTS = settings.PIPELINE_RETRY_MAX_ATTEMPTS
PIPELINE_RETRY_BASE_DELAY_SECONDS = settings.PIPELINE_RETRY_BASE_DELAY_SECONDS

AI_TYR_MODEL = settings.AI_TYR_MODEL
AI_REQUEST_TIMEOUT_SECONDS = settings.AI_REQUEST_TIMEOUT_SECONDS
AI_SCORING_ENABLED = settings.AI_SCORING_ENABLED
AI_SCORING_WEIGHT = settings.AI_SCORING_WEIGHT
AI_DETERMINISTIC_WEIGHT = settings.AI_DETERMINISTIC_WEIGHT
AI_MIN_CONFIDENCE = settings.AI_MIN_CONFIDENCE
AI_MIN_CONTEXT_QUALITY = settings.AI_MIN_CONTEXT_QUALITY
AI_MAX_EFFECTIVE_WEIGHT = settings.AI_MAX_EFFECTIVE_WEIGHT
AI_SCORING_MIN_DETERMINISTIC_SCORE = settings.AI_SCORING_MIN_DETERMINISTIC_SCORE
AI_SCORING_MIN_ROLE_MATCH = settings.AI_SCORING_MIN_ROLE_MATCH
AI_SCORING_MIN_SKILL_OVERLAP = settings.AI_SCORING_MIN_SKILL_OVERLAP
AI_MAX_CALLS_PER_RUN = settings.AI_MAX_CALLS_PER_RUN
AI_SCORING_CACHE_ENABLED = settings.AI_SCORING_CACHE_ENABLED
AI_SCORE_DESCRIPTION_MAX_CHARS = settings.AI_SCORE_DESCRIPTION_MAX_CHARS
AI_SCORE_REQUIREMENTS_MAX_CHARS = settings.AI_SCORE_REQUIREMENTS_MAX_CHARS
AI_SCORE_SUMMARY_MAX_CHARS = settings.AI_SCORE_SUMMARY_MAX_CHARS

RESUME_MAX_FILE_SIZE_BYTES = settings.RESUME_MAX_FILE_SIZE_BYTES
RESUME_ALLOWED_MIME_TYPES = [
    mime.strip().lower()
    for mime in settings.RESUME_ALLOWED_MIME_TYPES.split(",")
    if mime.strip()
]
RESUME_MIN_EXTRACTED_TEXT_CHARS = settings.RESUME_MIN_EXTRACTED_TEXT_CHARS
RESUME_AI_MAX_INPUT_CHARS = settings.RESUME_AI_MAX_INPUT_CHARS

ROLE_RANK_BY_NAME = {"BASIC": 1, "ADMIN": 2}

# Rate limiting (per path + IP; see core.security.rate_limit)
RATE_LIMIT_LOGIN_MAX_REQUESTS = 5
RATE_LIMIT_LOGIN_WINDOW_SECONDS = 300
RATE_LIMIT_FORGET_PASSWORD_MAX_REQUESTS = 3
RATE_LIMIT_FORGET_PASSWORD_WINDOW_SECONDS = 3600
RATE_LIMIT_VALIDATE_CODE_MAX_REQUESTS = 10
RATE_LIMIT_VALIDATE_CODE_WINDOW_SECONDS = 300
