from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    ENVIRONMENT: str = "development"
    API_PORT: int = 8000

    DB_HOST: str
    DB_PORT: int = 5432
    DB_USER: str
    DB_PASSWORD: str
    DB_NAME: str

    RABBITMQ_HOST: str
    RABBITMQ_PORT: int = 5672
    RABBITMQ_USER: str
    RABBITMQ_PASSWORD: str

    REDIS_HOST: str
    REDIS_PORT: int = 6379
    REDIS_PASSWORD: str = ""

    SECRET_KEY: str
    ALGORITHM: str = "HS256"
    ACCESS_TOKEN_EXPIRE_MINUTES: int = 1440

    SMTP_HOST: str
    SMTP_PORT: int = 587
    SMTP_USER: str
    SMTP_PASSWORD: str
    EMAIL_FROM: str

    ATS_GREENHOUSE_BOARDS: str = ""
    ATS_LEVER_COMPANIES: str = ""
    ATS_ASHBY_ORGANIZATIONS: str = ""
    ATS_WORKABLE_COMPANIES: str = ""
    ATS_WORKABLE_API_TOKEN: str = ""
    ATS_BREEZY_ORGANIZATIONS: str = ""
    ATS_SMARTRECRUITERS_COMPANIES: str = ""
    ATS_RECRUITEE_COMPANIES: str = ""
    ATS_GUPY_COMPANIES: str = ""
    ATS_GUPY_API_TOKEN: str = ""
    ATS_WORKDAY_COMPANIES: str = ""
    ATS_ENABLE_UNOFFICIAL_SOURCES: bool = True
    ATS_MAX_JOBS_PER_SOURCE: int = 200
    ATS_ENABLE_MOCK_FALLBACK: bool = True
    INGESTION_RELEVANCE_ENABLED: bool = True
    INGESTION_RELEVANCE_THRESHOLD: float = 0.35
    INGESTION_RELEVANCE_EXPLORATION_RATE: float = 0.15
    INGESTION_RELEVANCE_MIN_JOBS: int = 300
    INGESTION_ATS_EXPAND_ENABLED: bool = True
    INGESTION_ATS_EXPAND_MIN_JOBS: int = 40
    INGESTION_ATS_EXPAND_DAYS_RANGE: int = 30

    OPENAI_API_KEY: str = ""
    AI_TYR_MODEL: str = "gpt-5.1"
    AI_REQUEST_TIMEOUT_SECONDS: int = 30
    AI_SCORING_ENABLED: bool = True
    AI_SCORING_WEIGHT: float = 0.20
    AI_DETERMINISTIC_WEIGHT: float = 0.80
    AI_MIN_CONFIDENCE: float = 0.45
    AI_MIN_CONTEXT_QUALITY: float = 0.50
    AI_MAX_EFFECTIVE_WEIGHT: float = 0.40
    AI_SCORING_MIN_DETERMINISTIC_SCORE: float = 45.0
    AI_SCORING_MIN_ROLE_MATCH: float = 0.15
    AI_SCORING_MIN_SKILL_OVERLAP: float = 0.10
    AI_SCORING_MIN_LOCATION_SIGNAL: float = 0.20
    AI_SCORING_MIN_WORK_MODEL_SIGNAL: float = 0.20
    AI_SCORING_MAX_SENIORITY_GAP: int = 2
    AI_MAX_CALLS_PER_RUN: int = 75
    AI_SCORING_CACHE_ENABLED: bool = True
    AI_SCORE_DESCRIPTION_MAX_CHARS: int = 700
    AI_SCORE_REQUIREMENTS_MAX_CHARS: int = 700
    AI_SCORE_SUMMARY_MAX_CHARS: int = 400

    RESUME_MAX_FILE_SIZE_BYTES: int = 5242880
    RESUME_ALLOWED_MIME_TYPES: str = "application/pdf"
    RESUME_MIN_EXTRACTED_TEXT_CHARS: int = 80
    RESUME_AI_MAX_INPUT_CHARS: int = 12000

    PIPELINE_RUN_LOCK_TTL_SECONDS: int = 900
    PIPELINE_LAST_RUN_TTL_SECONDS: int = 86400
    PIPELINE_EVENT_DEDUPE_TTL_SECONDS: int = 21600
    GLOBAL_INGESTION_RUN_LOCK_TTL_SECONDS: int = 1800
    GLOBAL_INGESTION_LAST_RUN_TTL_SECONDS: int = 604800
    GLOBAL_INGESTION_DEFAULT_DAYS_RANGE: int = 14
    GLOBAL_INGESTION_SCHEDULER_INTERVAL_SECONDS: int = 900
    GLOBAL_INGESTION_SCHEDULE_HOUR_UTC: int = 6
    GLOBAL_CATALOG_RETENTION_DAYS: int = 45
    GLOBAL_CATALOG_CLEANUP_BATCH_SIZE: int = 1000
    GLOBAL_CATALOG_CLEANUP_INTERVAL_SECONDS: int = 900
    GLOBAL_CATALOG_CLEANUP_SCHEDULE_HOUR_UTC: int = 7
    GLOBAL_CATALOG_CLEANUP_LAST_RUN_TTL_SECONDS: int = 604800

    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8")


settings = Settings()

# Application constants (kept next to settings for one import surface)
COOKIE_AUTH = "auth"
COOKIE_AUTH_RESET = "auth_reset"

AUTH_COOKIE_MAX_AGE = 259200
RESET_COOKIE_MAX_AGE = 900
RESET_CODE_REDIS_TTL = 600

EMAIL_QUEUE = "email-queue"

INGESTION_JOBS_QUEUE = "ingestion.jobs"
JOBS_NORMALIZED_QUEUE = "jobs.normalized"
SCORING_JOBS_QUEUE = "scoring.jobs"
DIGEST_EMAIL_QUEUE = "digest.email"
GLOBAL_INGESTION_JOBS_QUEUE = "global.ingestion.jobs"

HTTP_CLIENT_TIMEOUT_SECONDS = 20.0
HTTP_CLIENT_MAX_CONNECTIONS = 100
HTTP_CLIENT_MAX_KEEPALIVE_CONNECTIONS = 20

ATS_GREENHOUSE_BOARDS = settings.ATS_GREENHOUSE_BOARDS
ATS_LEVER_COMPANIES = settings.ATS_LEVER_COMPANIES
ATS_ASHBY_ORGANIZATIONS = settings.ATS_ASHBY_ORGANIZATIONS
ATS_WORKABLE_COMPANIES = settings.ATS_WORKABLE_COMPANIES
ATS_WORKABLE_API_TOKEN = settings.ATS_WORKABLE_API_TOKEN
ATS_BREEZY_ORGANIZATIONS = settings.ATS_BREEZY_ORGANIZATIONS
ATS_SMARTRECRUITERS_COMPANIES = settings.ATS_SMARTRECRUITERS_COMPANIES
ATS_RECRUITEE_COMPANIES = settings.ATS_RECRUITEE_COMPANIES
ATS_GUPY_COMPANIES = settings.ATS_GUPY_COMPANIES
ATS_GUPY_API_TOKEN = settings.ATS_GUPY_API_TOKEN
ATS_WORKDAY_COMPANIES = settings.ATS_WORKDAY_COMPANIES
ATS_ENABLE_UNOFFICIAL_SOURCES = settings.ATS_ENABLE_UNOFFICIAL_SOURCES
ATS_MAX_JOBS_PER_SOURCE = settings.ATS_MAX_JOBS_PER_SOURCE
ATS_ENABLE_MOCK_FALLBACK = settings.ATS_ENABLE_MOCK_FALLBACK
INGESTION_RELEVANCE_ENABLED = settings.INGESTION_RELEVANCE_ENABLED
INGESTION_RELEVANCE_THRESHOLD = settings.INGESTION_RELEVANCE_THRESHOLD
INGESTION_RELEVANCE_EXPLORATION_RATE = settings.INGESTION_RELEVANCE_EXPLORATION_RATE
INGESTION_RELEVANCE_MIN_JOBS = settings.INGESTION_RELEVANCE_MIN_JOBS
INGESTION_ATS_EXPAND_ENABLED = settings.INGESTION_ATS_EXPAND_ENABLED
INGESTION_ATS_EXPAND_MIN_JOBS = settings.INGESTION_ATS_EXPAND_MIN_JOBS
INGESTION_ATS_EXPAND_DAYS_RANGE = settings.INGESTION_ATS_EXPAND_DAYS_RANGE

PIPELINE_RUN_LOCK_KEY_PREFIX = "pipeline:run:lock"
PIPELINE_LAST_RUN_KEY_PREFIX = "pipeline:run:last"
PIPELINE_RUN_METRICS_KEY_PREFIX = "pipeline:run:metrics"
PIPELINE_SCORING_PROGRESS_KEY_PREFIX = "pipeline:run:scoring:processed"
PIPELINE_SCORING_FAILED_KEY_PREFIX = "pipeline:run:scoring:failed"
PIPELINE_SCORING_DIGEST_TRIGGER_KEY_PREFIX = "pipeline:run:scoring:digest_triggered"
PIPELINE_RUN_AI_CALLS_KEY_PREFIX = "pipeline:run:ai:calls"
PIPELINE_RUN_AI_CACHE_HITS_KEY_PREFIX = "pipeline:run:ai:cache_hits"
PIPELINE_RUN_AI_CACHE_MISSES_KEY_PREFIX = "pipeline:run:ai:cache_misses"
PIPELINE_RUN_AI_SKIPPED_KEY_PREFIX = "pipeline:run:ai:skipped"
PIPELINE_RUN_AI_PREFILTER_REJECTED_KEY_PREFIX = "pipeline:run:ai:prefilter_rejected"
PIPELINE_RUN_AI_PREFILTER_REASON_KEY_PREFIX = "pipeline:run:ai:prefilter_reason"
PIPELINE_RUN_LOCK_TTL_SECONDS = settings.PIPELINE_RUN_LOCK_TTL_SECONDS
PIPELINE_LAST_RUN_TTL_SECONDS = settings.PIPELINE_LAST_RUN_TTL_SECONDS
PIPELINE_EVENT_DEDUPE_KEY_PREFIX = "pipeline:event:dedupe"
PIPELINE_EVENT_DEDUPE_TTL_SECONDS = settings.PIPELINE_EVENT_DEDUPE_TTL_SECONDS
GLOBAL_INGESTION_EVENT_DEDUPE_KEY_PREFIX = "global_ingestion:event:dedupe"
GLOBAL_INGESTION_RUN_LOCK_KEY_PREFIX = "global_ingestion:run:lock"
GLOBAL_INGESTION_LAST_RUN_KEY_PREFIX = "global_ingestion:run:last"
GLOBAL_INGESTION_RUN_LOCK_TTL_SECONDS = settings.GLOBAL_INGESTION_RUN_LOCK_TTL_SECONDS
GLOBAL_INGESTION_LAST_RUN_TTL_SECONDS = settings.GLOBAL_INGESTION_LAST_RUN_TTL_SECONDS
GLOBAL_INGESTION_DEFAULT_DAYS_RANGE = settings.GLOBAL_INGESTION_DEFAULT_DAYS_RANGE
GLOBAL_INGESTION_SCHEDULER_INTERVAL_SECONDS = settings.GLOBAL_INGESTION_SCHEDULER_INTERVAL_SECONDS
GLOBAL_INGESTION_SCHEDULE_HOUR_UTC = settings.GLOBAL_INGESTION_SCHEDULE_HOUR_UTC
GLOBAL_CATALOG_CLEANUP_LOCK_KEY_PREFIX = "global_catalog:cleanup:lock"
GLOBAL_CATALOG_CLEANUP_LAST_RUN_KEY_PREFIX = "global_catalog:cleanup:last"
GLOBAL_CATALOG_RETENTION_DAYS = settings.GLOBAL_CATALOG_RETENTION_DAYS
GLOBAL_CATALOG_CLEANUP_BATCH_SIZE = settings.GLOBAL_CATALOG_CLEANUP_BATCH_SIZE
GLOBAL_CATALOG_CLEANUP_INTERVAL_SECONDS = settings.GLOBAL_CATALOG_CLEANUP_INTERVAL_SECONDS
GLOBAL_CATALOG_CLEANUP_SCHEDULE_HOUR_UTC = settings.GLOBAL_CATALOG_CLEANUP_SCHEDULE_HOUR_UTC
GLOBAL_CATALOG_CLEANUP_LAST_RUN_TTL_SECONDS = settings.GLOBAL_CATALOG_CLEANUP_LAST_RUN_TTL_SECONDS

AI_TYR_MODEL = settings.AI_TYR_MODEL
AI_REQUEST_TIMEOUT_SECONDS = settings.AI_REQUEST_TIMEOUT_SECONDS
AI_SCORING_ENABLED = settings.AI_SCORING_ENABLED
AI_SCORING_WEIGHT = settings.AI_SCORING_WEIGHT
AI_DETERMINISTIC_WEIGHT = settings.AI_DETERMINISTIC_WEIGHT
AI_MIN_CONFIDENCE = settings.AI_MIN_CONFIDENCE
AI_MIN_CONTEXT_QUALITY = settings.AI_MIN_CONTEXT_QUALITY
AI_MAX_EFFECTIVE_WEIGHT = settings.AI_MAX_EFFECTIVE_WEIGHT
AI_SCORING_MIN_DETERMINISTIC_SCORE = settings.AI_SCORING_MIN_DETERMINISTIC_SCORE
AI_SCORING_MIN_ROLE_MATCH = settings.AI_SCORING_MIN_ROLE_MATCH
AI_SCORING_MIN_SKILL_OVERLAP = settings.AI_SCORING_MIN_SKILL_OVERLAP
AI_SCORING_MIN_LOCATION_SIGNAL = settings.AI_SCORING_MIN_LOCATION_SIGNAL
AI_SCORING_MIN_WORK_MODEL_SIGNAL = settings.AI_SCORING_MIN_WORK_MODEL_SIGNAL
AI_SCORING_MAX_SENIORITY_GAP = settings.AI_SCORING_MAX_SENIORITY_GAP
AI_MAX_CALLS_PER_RUN = settings.AI_MAX_CALLS_PER_RUN
AI_SCORING_CACHE_ENABLED = settings.AI_SCORING_CACHE_ENABLED
AI_SCORE_DESCRIPTION_MAX_CHARS = settings.AI_SCORE_DESCRIPTION_MAX_CHARS
AI_SCORE_REQUIREMENTS_MAX_CHARS = settings.AI_SCORE_REQUIREMENTS_MAX_CHARS
AI_SCORE_SUMMARY_MAX_CHARS = settings.AI_SCORE_SUMMARY_MAX_CHARS

RESUME_MAX_FILE_SIZE_BYTES = settings.RESUME_MAX_FILE_SIZE_BYTES
RESUME_ALLOWED_MIME_TYPES = [
    mime.strip().lower()
    for mime in settings.RESUME_ALLOWED_MIME_TYPES.split(",")
    if mime.strip()
]
RESUME_MIN_EXTRACTED_TEXT_CHARS = settings.RESUME_MIN_EXTRACTED_TEXT_CHARS
RESUME_AI_MAX_INPUT_CHARS = settings.RESUME_AI_MAX_INPUT_CHARS

ROLE_RANK_BY_NAME = {"BASIC": 1, "ADMIN": 2}

# Rate limiting (per path + IP; see core.security.rate_limit)
RATE_LIMIT_LOGIN_MAX_REQUESTS = 5
RATE_LIMIT_LOGIN_WINDOW_SECONDS = 300
RATE_LIMIT_FORGET_PASSWORD_MAX_REQUESTS = 3
RATE_LIMIT_FORGET_PASSWORD_WINDOW_SECONDS = 3600
RATE_LIMIT_VALIDATE_CODE_MAX_REQUESTS = 10
RATE_LIMIT_VALIDATE_CODE_WINDOW_SECONDS = 300

